#!/bin/sh

set -e
docker version >/dev/null 2>/dev/null

CONTAINERS=$(docker ps -a | grep runner | grep project | grep concurrent | grep cache)

echo Clearing docker cache...
for container in $(echo "$CONTAINERS" | awk '{print $1}'); do
    docker rm -v $container || :
done
