#!/bin/sh

set -e

# detect user: first try to use gitlab_ci_multi_runner
for USER in gitlab_ci_multi_runner gitlab_runner; do
  if id -u "$USER" &>/dev/null; then
    echo "GitLab Runner: detected $USER"
    continue
  fi
done

# create user if doesn't exist: it will create gitlab_runner if not found
if ! id -u "$USER" &>/dev/null; then
  echo "GitLab Runner: creating $USER"
  useradd --comment 'GitLab Runner' --create-home $USER
fi

# add user to docker group to allow Docker access (insecure)
if usermod -aG docker $USER; then
  echo "GitLab Runner: added $USER to docker group (insecure)"
fi

# create empty config and re-register runner
eval HOMEDIR=~$USER
cd $HOMEDIR
touch config.toml
chown $USER:$USER config.toml
chmod 0600 config.toml

# re-register runner
gitlab-ci-multi-runner stop &>/dev/null || :
gitlab-ci-multi-runner uninstall &>/dev/null || :
gitlab-ci-multi-runner install --user=$USER

# start runner service
service gitlab-ci-multi-runner start || :
