deps:
		vagrant plugin install vagrant-parallels

virtualbox:
		vagrant up --provider=virtualbox --provision virtualbox
		vagrant halt -f virtualbox

parallels:
		vagrant up --provider=parallels --provision parallels
		vagrant halt -f parallels
