#! /bin/bash

### BEGIN INIT INFO
# Provides:          gitlab-ci-multi-runner
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GitLab CI-Multi Runner init.d script
# Description: Enables automatic start of runners at boot time in the background.
### END INIT INFO

DESC="GitLab CI-Multi Runner"
USER="gitlab_ci_multi_runner"
GROUP="gitlab_ci_multi_runner"
CHDIR="~$USER"
NAME="gitlab-ci-multi-runner"
DAEMON="/usr/bin/gitlab-ci-multi-runner"
PIDFILE="/var/run/gitlab-ci-multi-runner.pid"
LOGFILE="/var/log/gitlab-ci-multi-runner.log"

# Exit if the package is not installed
if [ ! -x "$DAEMON" ]; then
  echo "$DAEMON not present or not executable"
  exit 1
fi

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Define LSB log_* functions.
. /lib/lsb/init-functions

## Check to see if we are running as root first.
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

eval CHDIR=$CHDIR

do_start() {
  start-stop-daemon --start \
    --pidfile "$PIDFILE" \
    --chdir "$CHDIR" \
    --background \
    --make-pidfile \
    --chuid "$USER:$GROUP" \
    --no-close \
    --exec "$DAEMON" -- "run" &>> $LOGFILE
}

do_stop() {
  start-stop-daemon --stop --pidfile "$PIDFILE" --user "$USER" --exec "$DAEMON" --quiet
}

case "$1" in
  start)
    log_daemon_msg "Starting $DESC"
    do_start
    log_end_msg $?
    ;;
  stop)
    log_daemon_msg "Stopping $DESC"
    do_stop
    log_end_msg $?
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p "$PIDFILE" "$DAEMON" "$DESC"
    ;;
  *)
    echo "Usage: sudo service gitlab-ci-multi-runner {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
